USE BlogExampleDb;

/*
DROP TABLE BlogPostTag;
DROP TABLE Tag;
DROP TABLE BlogPost;


CREATE TABLE Tag (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL,
	DisplayName NVARCHAR(MAX) NOT NULL
);

CREATE TABLE BlogPost (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Heading NVARCHAR(MAX) NOT NULL,
	PageTitle NVARCHAR(MAX) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	ShortDescription NVARCHAR(MAX) NOT NULL,
	FeaturedImageUrl NVARCHAR(MAX) NOT NULL,
	UrlHandle NVARCHAR(MAX) NOT NULL,
	PublishedDate DATETIME2 NOT NULL,
	Author NVARCHAR(MAX) NOT NULL,
	Visible BIT NOT NULL
);


CREATE TABLE BlogPostTag (
	BlogPostId UNIQUEIDENTIFIER NOT NULL,
	TagId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_BlogPostTag] PRIMARY KEY(BlogPostId, TagId),
	CONSTRAINT [FK_BlogPostTag_BlogPostId] FOREIGN KEY(BlogPostId) REFERENCES [BlogPost] (Id) ON DELETE CASCADE,
	CONSTRAINT [FK_BlogPostTag_TagId] FOREIGN KEY(TagId) REFERENCES [Tag] (Id) ON DELETE CASCADE
);

*/
--DELETE FROM Tag

SELECT * FROM BlogPost
SELECT * FROM Tag
SELECT * FROM BlogPostTag

